// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_Yoon.Models;

#nullable disable

namespace Mission06_Yoon.Migrations
{
    [DbContext(typeof(MovieAddedContext))]
    [Migration("20240223082050_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Mission06_Yoon.Models.AddingMovie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CopiedToPlex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent_To")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.HasIndex("CategoryId");

                    b.ToTable("MoviesAdded");
                });

            modelBuilder.Entity("Mission06_Yoon.Models.Categories", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("CategoryTable");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Category = "Miscellaneous"
                        },
                        new
                        {
                            CategoryId = 2,
                            Category = "Drama"
                        },
                        new
                        {
                            CategoryId = 3,
                            Category = "Magic"
                        },
                        new
                        {
                            CategoryId = 4,
                            Category = "Television"
                        },
                        new
                        {
                            CategoryId = 5,
                            Category = "Horror/Suspense"
                        },
                        new
                        {
                            CategoryId = 6,
                            Category = "Comedy"
                        },
                        new
                        {
                            CategoryId = 7,
                            Category = "Family"
                        },
                        new
                        {
                            CategoryId = 8,
                            Category = "Action/Adventure"
                        },
                        new
                        {
                            CategoryId = 9,
                            Category = "VHS"
                        });
                });

            modelBuilder.Entity("Mission06_Yoon.Models.AddingMovie", b =>
                {
                    b.HasOne("Mission06_Yoon.Models.Categories", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
